Repository MogakCote/mogak-codingtest, pull requests merged in 2024-09, with the labels that each got.

#42 feat: SecretKey 암호화 알고리즘 평문 -> base64 decode, hmacShaKey 변경
  src/main/java/com/ormi/mogakcote/security/service/JwtService.java
  src/main/resources/config/application-dev.yml
Labels: Domain: Backend, P2

#50 error: AuthUser 바인딩 수정
  src/main/java/com/ormi/mogakcote/config/web/MvcConfigurer.java
  src/main/java/com/ormi/mogakcote/security/service/JwtService.java
  src/main/java/com/ormi/mogakcote/user/application/UserService.java
  src/main/java/com/ormi/mogakcote/user/presentation/UserController.java
Labels: Domain: Backend, P2

#52 Feat: Post CRUD 기능 구현
  src/main/java/com/ormi/mogakcote/exception/dto/ErrorType.java
  src/main/java/com/ormi/mogakcote/post/application/PostService.java
  src/main/java/com/ormi/mogakcote/post/domain/Post.java
  src/main/java/com/ormi/mogakcote/post/domain/PostFlag.java
  src/main/java/com/ormi/mogakcote/post/domain/ReportFlag.java
  src/main/java/com/ormi/mogakcote/post/dto/request/PostRequest.java
  src/main/java/com/ormi/mogakcote/post/dto/response/PostResponse.java
  src/main/java/com/ormi/mogakcote/post/exception/AuthInvalidException.java
  src/main/java/com/ormi/mogakcote/post/exception/PostInvalidException.java
  src/main/java/com/ormi/mogakcote/post/infrastructure/PostRepository.java
  src/main/java/com/ormi/mogakcote/post/presentation/PostController.java
  src/main/java/com/ormi/mogakcote/problem/domain/Algorithm.java
  src/main/java/com/ormi/mogakcote/problem/domain/PostAlgorithm.java
  src/main/java/com/ormi/mogakcote/problem/infrastructure/PostAlgorithmRepository.java
Labels: Domain: Backend, P2

#55 Fix: problem entity attribute -> id로 변환
  src/main/java/com/ormi/mogakcote/problem/application/AlgorithmService.java
  src/main/java/com/ormi/mogakcote/problem/application/LanguageService.java
  src/main/java/com/ormi/mogakcote/problem/application/PlatformServcie.java
  src/main/java/com/ormi/mogakcote/problem/domain/Language.java
  src/main/java/com/ormi/mogakcote/problem/domain/Platform.java
  src/main/java/com/ormi/mogakcote/problem/dto/request/AlgorithmRequest.java
  src/main/java/com/ormi/mogakcote/problem/dto/request/LanguageRequest.java
  src/main/java/com/ormi/mogakcote/problem/dto/request/PlatformRequest.java
  src/main/java/com/ormi/mogakcote/problem/dto/response/AlgorithmResponse.java
  src/main/java/com/ormi/mogakcote/problem/dto/response/LanguageResponse.java
  src/main/java/com/ormi/mogakcote/problem/dto/response/PlatformResponse.java
  src/main/java/com/ormi/mogakcote/problem/infrastructure/AlgorithmRepository.java
  src/main/java/com/ormi/mogakcote/problem/infrastructure/LanguageRepository.java
  src/main/java/com/ormi/mogakcote/problem/infrastructure/PlatformRepository.java
  src/main/java/com/ormi/mogakcote/problem/presentation/AlgorithmController.java
  src/main/java/com/ormi/mogakcote/problem/presentation/LanguageController.java
  src/main/java/com/ormi/mogakcote/problem/presentation/PlatformController.java
Labels: Domain: Backend, P1

#57 Domain: 관리자페이지 사용자 권한 관리
  src/main/java/com/ormi/mogakcote/exception/auth/UserAuthManagementInvalidException.java
  src/main/java/com/ormi/mogakcote/exception/dto/ErrorType.java
  src/main/java/com/ormi/mogakcote/user/application/UserService.java
  src/main/java/com/ormi/mogakcote/user/domain/Authority.java
  src/main/java/com/ormi/mogakcote/user/domain/User.java
  src/main/java/com/ormi/mogakcote/user/dto/request/UserAuthRequest.java
  src/main/java/com/ormi/mogakcote/user/dto/response/UserAuthResponse.java
  src/main/java/com/ormi/mogakcote/user/presentation/UserController.java
Labels: Domain: Backend, P1

#58 Fix: access token null check 추가
  src/main/java/com/ormi/mogakcote/security/argumentResolver/AuthUserResolver.java
Labels: Domain: Backend, P2

#61 Feat :사용자 프로필 수정 기능 구현 #21
  build.gradle
  src/main/java/com/ormi/mogakcote/post/infrastructure/PostRepository.java
  src/main/java/com/ormi/mogakcote/profile/application/UserProfileService.java
  src/main/java/com/ormi/mogakcote/profile/presentation/UserProfileController.java
  src/main/java/com/ormi/mogakcote/user/application/UserService.java
  src/main/java/com/ormi/mogakcote/user/domain/User.java
  src/main/java/com/ormi/mogakcote/user/dto/request/ChangePasswordRequest.java
  src/main/java/com/ormi/mogakcote/user/dto/request/DeleteUserRequest.java
  src/main/java/com/ormi/mogakcote/user/dto/request/UpdateProfileRequest.java
  src/main/java/com/ormi/mogakcote/user/infrastructure/UserRepository.java
  src/main/java/com/ormi/mogakcote/user/presentation/UserController.java
Labels: Domain: Backend, P2

#60 feat: 관리자 -> 게시글 숨김처리
  src/main/java/com/ormi/mogakcote/admin/presentation/AdminController.java
  src/main/java/com/ormi/mogakcote/post/application/PostService.java
  src/main/java/com/ormi/mogakcote/post/domain/Post.java
  src/main/java/com/ormi/mogakcote/post/presentation/PostController.java
  src/main/java/com/ormi/mogakcote/problem/presentation/AlgorithmController.java
Labels: Domain: Backend, P1

#73 Feature : 회원가입, 마이프로필, 마이프로필 수정 UI
  build.gradle
  src/main/java/com/ormi/mogakcote/post/infrastructure/PostRepository.java
  src/main/java/com/ormi/mogakcote/profile/application/UserProfileService.java
  src/main/java/com/ormi/mogakcote/profile/presentation/UserProfileController.java
  src/main/java/com/ormi/mogakcote/user/application/UserService.java
  src/main/java/com/ormi/mogakcote/user/domain/User.java
  src/main/java/com/ormi/mogakcote/user/infrastructure/UserRepository.java
  src/main/java/com/ormi/mogakcote/user/presentation/UserController.java
  src/main/resources/templates/profile.html
  src/main/resources/templates/profileedit.html
  src/main/resources/templates/signup.html
Labels: Domain: Frontend, P2, P0

#85 feat: 메인 페이지 UI 구현
  src/main/java/com/ormi/mogakcote/badge/presentation/BadgeController.java
  src/main/java/com/ormi/mogakcote/badge/presentation/UserBadgeController.java
  src/main/java/com/ormi/mogakcote/post/application/PostService.java
  src/main/java/com/ormi/mogakcote/post/dto/request/PostSearchRequest.java
  src/main/java/com/ormi/mogakcote/post/dto/request/SortType.java
  src/main/java/com/ormi/mogakcote/post/dto/response/PostSearchResponse.java
  src/main/java/com/ormi/mogakcote/post/infrastructure/PostRepositoryImpl.java
  src/main/java/com/ormi/mogakcote/post/presentation/PostController.java
  src/main/java/com/ormi/mogakcote/security/config/SecurityConfig.java
  src/main/java/com/ormi/mogakcote/user/infrastructure/UserRepository.java
  src/main/resources/static/css/post/list.css
  src/main/resources/static/img/page-arrow-active.svg
  src/main/resources/static/img/page-arrow-disabled.svg
  src/main/resources/static/img/select-arrow.svg
  src/main/resources/templates/post/list.html
Labels: Domain: Frontend, P2

#97 feat: 게시글 UI 구현
  src/main/java/com/ormi/mogakcote/post/application/PostService.java
  src/main/java/com/ormi/mogakcote/post/presentation/PostApiController.java
  src/main/java/com/ormi/mogakcote/post/presentation/PostViewController.java
  src/main/resources/templates/post/post-detail.html
  src/main/resources/templates/post/post-edit.html
  src/main/resources/templates/post/post.html
Labels: P1

#83 feat: 인증/권한 UI, 스크립트 추가. JWT cookie path 추가
  src/main/java/com/ormi/mogakcote/security/service/JwtService.java
  src/main/resources/static/css/auth.css
  src/main/resources/static/js/auth/apiConfig.js
  src/main/resources/static/js/auth/error.js
  src/main/resources/static/js/auth/findEmail.js
  src/main/resources/static/js/auth/findPassword.js
  src/main/resources/static/js/auth/init.js
  src/main/resources/static/js/auth/jwt.js
  src/main/resources/static/js/auth/login.js
  src/main/resources/static/js/auth/logout.js
  src/main/resources/templates/auth/findEmail.html
  src/main/resources/templates/auth/findPassword.html
  src/main/resources/templates/auth/login.html
Labels: Domain: Frontend, P1

#105 fix/post UI 27
  src/main/java/com/ormi/mogakcote/post/application/PostService.java
  src/main/java/com/ormi/mogakcote/post/presentation/PostApiController.java
  src/main/java/com/ormi/mogakcote/post/presentation/PostViewController.java
  src/main/resources/templates/post/post-create.html
  src/main/resources/templates/post/post-detail.html
  src/main/resources/templates/post/post-modify.html
Labels: Domain: Frontend, P1
